# Usa la imagen oficial de Node.js 18 como base
FROM node:18-alpine

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el package.json y el package-lock.json (si existe)
COPY package*.json ./

# Instalar las dependencias de la aplicación
RUN npm install

# Instalar la versión específica de Angular CLI compatible con el proyecto
RUN npm install -g @angular/cli@16.2.9

# Verificar la versión de Angular CLI y Node.js
RUN ng version
RUN node -v

# Copiar el resto de la aplicación
COPY . .

# Exponer el puerto 4200 para acceder a la aplicación Angular
EXPOSE 4200

# Comando para iniciar la aplicación en modo de desarrollo
CMD ["ng", "serve", "--host", "0.0.0.0"]
