version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_biblioteca
    ports:
      - "3306:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: flask_backend
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      MYSQL_HOST: mysql_biblioteca
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "5500:5000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    container_name: angular_front
    ports:
      - "4200:80"
    depends_on:
      - backend

networks:
  my-network:

volumes:
  mysql_data:
