version: '3.8'

services:
  db:
    build: ./BBDD
    container_name: mysql_biblioteca
    ports:
      - "3307:3307"  
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

  backend:
    build: ./backend
    container_name: flask_backend
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      MYSQL_HOST: db  
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "5500:5000"
    depends_on:
      - db
    networks:
      - my-network

  frontend:
    build: ./frontend
    container_name: angular_front
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - my-network
      
networks:
  my-network:
    driver: bridge

volumes:
  mysql_data:
